# This file was generated by GoReleaser. DO NOT EDIT.
cask "crossmem" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "8b70d5f262b689974f5ae7b98aa704c4df751d69fa6639901f9d90fec60fc867"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9a1d18bc56a6443a7aee671959744d8b46389d75b882e01f65a8d31847c9697"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6fe70b110c713ad89f99712e2d8d3d43ed2bd3502cce5d8a75683b2b9e821c8"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a497a21e4156d9c9ee8a36ae7ac73ebf1bd5db57df9e07db7239225e6296032"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crossmem"
  desc "Portable context memory across local agent tools."
  homepage "https://github.com/muthuishere/crossmemcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crossmem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crossmem"]
    end
  end

  # No zap stanza required

end
