# This file was generated by GoReleaser. DO NOT EDIT.
cask "crossmem" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "1482d363c79db2b32e8be0e8d117791318c137cc1813a9a1932efd78ade94d58"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97b22e76d3918155c4c9098bb8aa8522d72de760f266f6632ccbec0133fce2ac"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e538c7467a64175559b9ae8dec72bc0361c885a23288166f76c5d1f8e2296034"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed382dd7e1e11243b6bb5a41c866f855b231d910754aeeeada5807acc31d009a"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crossmem"
  desc "Portable context memory across local agent tools."
  homepage "https://github.com/muthuishere/crossmemcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crossmem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crossmem"]
    end
  end

  # No zap stanza required

end
