# This file was generated by GoReleaser. DO NOT EDIT.
cask "crossmem" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "86febfb9e0517cd689a099fefba95d72ac65c8c933dfcf2ca664a1d931c4fbdf"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "22a7213546a69d18ace7446a09f2ac301524c933865e5b64b0d192ef722ea8b3"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e041b2062765db3528d64d0324a0da193d79d406cbe24a3aaf168fc9e2f45bb2"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "edbdc14550af1cc44f7af85ff147db4f4a956d53e5e9905de8f7f5dcab591112"
      url "https://github.com/muthuishere/crossmemcli/releases/download/v#{version}/crossmem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crossmem"
  desc "Portable context memory across local agent tools."
  homepage "https://github.com/muthuishere/crossmemcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crossmem"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crossmem"]
    end
  end

  # No zap stanza required

end
